apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-api.fullname" . }}
  labels:
    app: {{ include "todo-api.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "todo-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "todo-api.name" . }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: todo-api-sa
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        {{- range $k, $v in .Values.env }}
        - name: {{ $k }}
          value: "{{ $v }}"
        {{- end }}
        readinessProbe:
          httpGet: { path: /healthz, port: 8080 }
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /healthz, port: 8080 }
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-api.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "todo-api.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
